Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "userapi-vm"

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5432, host: 5433

  config.vm.provider "virtualbox" do |vb|
    vb.name = "UserAPI-VM"
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Sync the userapi folder into the VM
  config.vm.synced_folder "../userapi", "/home/vagrant/userapi"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook       = "playbooks/setup.yml"
    ansible.inventory_path = "playbooks/inventory.ini"
    ansible.limit          = "all"
    ansible.verbose        = false
  end
end
